# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtasker
  labels:
    app: airtasker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtasker
  template:
    metadata:
      labels:
        app: airtasker
    spec:
      containers:
      - name: airtasker
        image: ztnie/airtasker-demo
        env:
          - name: APP_NAME
            value: "airtasker"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---
# Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: airtasker-service
  labels:
    app: airtasker
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: airtasker